server:
  port: 9090
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gsjagdale/shri-app-config.git

management:
  security:
    enabled: false